version: 2
updates:
  - package-ecosystem: "github-actions"
    directories: 
      - "/"
      - "/tools/credential-scanning"
      - "/tools/sbom-aggregation"
      - "/tools/fork-support"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories: 
      - "/"
      - "/tools/credential-scanning"
      - "/tools/sbom-aggregation"
      - "/tools/conventional-commits/repository-ruleset"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"