sonar.projectKey=National-Node-Net_ospo-resources
sonar.organization=national-node-net
sonar.sources=.
sonar.tests=.
sonar.exclusions=**/*.txt
sonar.text.file.suffixes=.txt,.rego
sonar.test.inclusions=**/*_test.rego, **/test_*.py
sonar.coverage.exclusions=**/*_test.rego, **/test_*.py
sonar.featureflag.cloud-security-enable-generic-yaml-and-json-analyzer=true
